require: sudo
language: node_js
services:
  - docker
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sudo yarn add global gulp-cli
cache:
  directories:
  - $HOME/.yarn-cache
env:
  - DOCKER_IMAGE=prodest/api-organograma-v1 SERVICE_NAME=api-organograma RANCHER_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a4680 RANCHER_STACK=api RANCHER_COMPOSE_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a4680/environments/1e56/composeconfig
script: 
  /bin/sh .travis.sh
deploy:
  provider: script
  script: /bin/sh .deploy.sh
  on:
    branch: master


    